#! /bin/sh
#
# RTEMS Documentation Project
#
# Copyright 2017 Chris Johns <chrisj@rtems.org>
# All rights reserved
#
# Public domain
#

#
# Exit on error.
#
set -e

#
# We run where the script is located.
#
cd $(dirname $0)

./rtems-doxygen-download
./rtems-doxygen-publish

exit 0
