#! /bin/sh
#
# RTEMS Documentation Project
#
# Copyright 2017 Chris Johns <chrisj@rtems.org>
# All rights reserved
#
# Public domain
#

#
# Exit on error.
#
set -e

#
# We run where the script is located.
#
cd $(dirname $0)

#
# The lock file.
#
LOCK=.cron-lock

#
# Trap to remove the lock file/
#
trap "rm -f ${LOCK}" EXIT

if [ ! -f .cron-lock ]; then
 touch ${LOCK}
 ./rtems-doxygen-upload
fi

exit 0
