#! /bin/sh
#
# RTEMS Documentation Project
#
# Copyright 2017 Chris Johns <chrisj@rtems.org>
# All rights reserved
#
# Public domain
#

#
# Exit on error.
#
set -e

#
# Executables
#
cp=/bin/cp
rm=/bin/rm

#
# The current directory.
#
current=/data/www/docs.rtems.org/branches

#
# The new docs
#
new=/usr/home/chrisj/docs/latest/new

#
# If there is a new directory we have something to publsh.
#
if [ -d ${new} ]; then
 ${rm} -rf ${current}.tags ${current}/*
 ${cp} -r ${new}/.tags ${new}/* ${current}/.
 ${rm} -rf ${new}
fi

exit 0
